name: Jest
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install --save-dev jest
    - name: Run tests
      run: npm run test 
    - name: Build
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./source
        recurse: true
        output_dir: ./documentation
